### ISSUE TITLE
Instagram Feed widget shows error occasionally

### ISSUE THREAD

**Issue by appscreo** [appscreo/easy-social-share-buttons3#19]
Error Details
=============
An error of type E_ERROR was caused in line 86 of the file /srv/htdocs/wp-content/plugins/easy-social-share-buttons3/lib/modules/instagram-feed/class-instagram-feed-widget.php. Error message: Uncaught Error: Call to undefined function essb_instagram_feed() in /srv/htdocs/wp-content/plugins/easy-social-share-buttons3/lib/modules/instagram-feed/class-instagram-feed-widget.php:86
Stack trace:
#0 /wordpress/core/5.3.2/wp-includes/class-wp-widget.php(518): ESSBInstagramFeedWidget->form(Array)
#1 /wordpress/core/5.3.2/wp-admin/includes/widgets.php(276): WP_Widget->form_callback(Array)
#2 /wordpress/core/5.3.2/wp-includes/class-wp-customize-widgets.php(1053): wp_widget_control(Array, Array)
#3 /wordpress/core/5.3.2/wp-includes/class-wp-customize-widgets.php(1001): WP_Customize_Widgets->get_widget_control(Array)
#4 /wordpress/core/5.3.2/wp-includes/class-wp-customize-widgets.php(690): WP_Customize_Widgets->get_available_widgets()
#5 /wordpress/core/5.3.2/wp-includes/class-wp-hook.php(288): WP_Customize_Widgets->enqueue_scripts(”)
#6 /wordpress/core/5.3.2/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/5.3.2/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#8 /wordpress/core/5.3.2/wp-admin/customize.php(123): do_action(‘customize_contr…’)
#9 {main}
thrown

**Comment by appscreo** [comment]
Fixed. Error appearing only on the Bimber WordPress theme. Reason still unknown why so.
